project_id = "smoo_control"

[db]
port = 54324
shadow_port = 54325
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54326

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080", "http://127.0.0.1:8080"]

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
