import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;
import 'package:smoo_control/core/config/supabase_app_config.dart';
import 'package:smoo_control/core/database/app_database.dart';
import 'package:smoo_control/core/database/open_database_connection.dart';
import 'package:smoo_control/core/di/register_auth_dependencies.dart';
import 'package:smoo_control/core/di/register_pos_dependencies.dart';
import 'package:smoo_control/core/session/current_operator_service.dart';
import 'package:smoo_control/core/session/current_remote_session_service.dart';
import 'package:smoo_control/core/session/current_restaurant_service.dart';
import 'package:smoo_control/features/admin_remote/data/repositories/supabase_admin_expenses_repository.dart';
import 'package:smoo_control/features/admin_remote/data/repositories/supabase_admin_repository.dart';
import 'package:smoo_control/features/audit/data/datasources/local_audit_log_datasource.dart';
import 'package:smoo_control/features/audit/data/repositories/audit_log_repository.dart';
import 'package:smoo_control/features/audit/domain/repositories/i_audit_log_repository.dart';
import 'package:smoo_control/features/audit/presentation/bloc/audit_log_bloc.dart';
import 'package:smoo_control/features/auth/data/services/remote_bootstrap_auth_service.dart';
import 'package:smoo_control/features/auth/domain/services/device_initialization_service.dart';
import 'package:smoo_control/features/cash_register/data/datasources/local_cash_register_datasource.dart';
import 'package:smoo_control/features/cash_register/data/repositories/cash_register_repository.dart';
import 'package:smoo_control/features/cash_register/domain/repositories/i_cash_register_repository.dart';
import 'package:smoo_control/features/cash_register/presentation/bloc/cash_register_bloc.dart';
import 'package:smoo_control/features/catalog/data/datasources/local_catalog_datasource.dart';
import 'package:smoo_control/features/catalog/data/repositories/catalog_repository.dart';
import 'package:smoo_control/features/catalog/domain/repositories/i_catalog_repository.dart';
import 'package:smoo_control/features/catalog/presentation/bloc/catalog_bloc.dart';
import 'package:smoo_control/features/exchange_rates/data/datasources/local_exchange_rate_datasource.dart';
import 'package:smoo_control/features/exchange_rates/data/repositories/exchange_rate_repository.dart';
import 'package:smoo_control/features/exchange_rates/domain/repositories/i_exchange_rate_repository.dart';
import 'package:smoo_control/features/expenses/data/datasources/local_expenses_datasource.dart';
import 'package:smoo_control/features/expenses/data/repositories/expenses_repository.dart';
import 'package:smoo_control/features/expenses/domain/repositories/i_expenses_repository.dart';
import 'package:smoo_control/features/expenses/presentation/bloc/expenses_bloc.dart';
import 'package:smoo_control/features/inventory/data/datasources/local_inventory_datasource.dart';
import 'package:smoo_control/features/inventory/data/repositories/inventory_repository.dart';
import 'package:smoo_control/features/inventory/data/services/supabase_inventory_admin_read_service.dart';
import 'package:smoo_control/features/inventory/data/services/supabase_inventory_admin_write_service.dart';
import 'package:smoo_control/features/inventory/domain/repositories/i_inventory_repository.dart';
import 'package:smoo_control/features/modifiers/data/datasources/local_modifiers_datasource.dart';
import 'package:smoo_control/features/modifiers/data/repositories/modifiers_repository.dart';
import 'package:smoo_control/features/modifiers/domain/repositories/i_modifiers_repository.dart';
import 'package:smoo_control/features/modifiers/presentation/bloc/modifiers_bloc.dart';
import 'package:smoo_control/features/packaging/data/datasources/local_packaging_datasource.dart';
import 'package:smoo_control/features/packaging/data/repositories/packaging_repository.dart';
import 'package:smoo_control/features/packaging/domain/repositories/i_packaging_repository.dart';
import 'package:smoo_control/features/payment_methods/data/datasources/local_payment_methods_datasource.dart';
import 'package:smoo_control/features/payment_methods/data/repositories/payment_methods_repository.dart';
import 'package:smoo_control/features/payment_methods/domain/repositories/i_payment_methods_repository.dart';
import 'package:smoo_control/features/payment_methods/presentation/bloc/payment_methods_bloc.dart';
import 'package:smoo_control/features/products/data/datasources/local_products_datasource.dart';
import 'package:smoo_control/features/products/data/repositories/products_repository.dart';
import 'package:smoo_control/features/products/domain/repositories/i_products_repository.dart';
import 'package:smoo_control/features/products/presentation/bloc/products_bloc.dart';
import 'package:smoo_control/features/reports/data/services/supabase_daily_sales_report_service.dart';
import 'package:smoo_control/features/reports/data/services/supabase_expenses_report_service.dart';
import 'package:smoo_control/features/reports/data/services/supabase_inventory_value_report_service.dart';
import 'package:smoo_control/features/reports/data/services/supabase_report_summary_service.dart';
import 'package:smoo_control/features/reports/domain/services/i_remote_report_summary_service.dart';
import 'package:smoo_control/features/reports/domain/services/report_summary_service.dart';
import 'package:smoo_control/features/reports/presentation/bloc/reports_bloc.dart';
import 'package:smoo_control/features/roles/data/datasources/local_roles_datasource.dart';
import 'package:smoo_control/features/roles/data/repositories/roles_repository.dart';
import 'package:smoo_control/features/roles/domain/repositories/i_roles_repository.dart';
import 'package:smoo_control/features/roles/domain/services/access_control_service.dart';
import 'package:smoo_control/features/roles/domain/services/access_seed_service.dart';
import 'package:smoo_control/features/roles/presentation/bloc/roles_bloc.dart';
import 'package:smoo_control/features/sales/data/datasources/local_sales_datasource.dart';
import 'package:smoo_control/features/sales/data/repositories/sales_repository.dart';
import 'package:smoo_control/features/sales/data/repositories/supabase_sales_admin_repository.dart';
import 'package:smoo_control/features/sales/domain/repositories/i_sales_repository.dart';
import 'package:smoo_control/features/sales/domain/services/sale_invoice_pdf_service.dart';
import 'package:smoo_control/features/sales/presentation/bloc/sales_bloc.dart';
import 'package:smoo_control/features/settings/data/datasources/local_business_settings_datasource.dart';
import 'package:smoo_control/features/settings/data/repositories/business_settings_repository.dart';
import 'package:smoo_control/features/settings/domain/repositories/i_business_settings_repository.dart';
import 'package:smoo_control/features/settings/presentation/bloc/business_settings_bloc.dart';
import 'package:smoo_control/features/staff/data/datasources/local_staff_datasource.dart';
import 'package:smoo_control/features/staff/data/repositories/staff_pos_repository.dart';
import 'package:smoo_control/features/staff/data/repositories/supabase_staff_admin_repository.dart';
import 'package:smoo_control/features/staff/domain/repositories/i_staff_repository.dart';
import 'package:smoo_control/features/sync/data/datasources/local_sync_queue_datasource.dart';
import 'package:smoo_control/features/sync/data/datasources/local_sync_settings_datasource.dart';
import 'package:smoo_control/features/sync/data/datasources/supabase_catalog_pull_service.dart';
import 'package:smoo_control/features/sync/data/datasources/supabase_sync_remote_sender.dart';
import 'package:smoo_control/features/sync/data/repositories/sync_queue_repository.dart';
import 'package:smoo_control/features/sync/data/repositories/sync_settings_repository.dart';
import 'package:smoo_control/features/sync/domain/repositories/i_sync_queue_repository.dart';
import 'package:smoo_control/features/sync/domain/repositories/i_sync_settings_repository.dart';
import 'package:smoo_control/features/sync/domain/services/admin_data_refresh_service.dart';
import 'package:smoo_control/features/sync/domain/services/i_catalog_pull_service.dart';
import 'package:smoo_control/features/sync/domain/services/i_sync_remote_sender.dart';
import 'package:smoo_control/features/sync/domain/services/sync_queue_processor.dart';
import 'package:smoo_control/features/sync/domain/services/sync_scheduler_service.dart';
import 'package:smoo_control/features/sync/presentation/bloc/sync_bloc.dart';
import 'package:smoo_control/features/system/data/services/pilot_operation_reset_service.dart';
import 'package:smoo_control/features/tables/data/datasources/local_tables_datasource.dart';
import 'package:smoo_control/features/tables/data/repositories/tables_repository.dart';
import 'package:smoo_control/features/tables/domain/repositories/i_tables_repository.dart';
import 'package:smoo_control/features/tables/presentation/bloc/tables_bloc.dart';
import 'package:smoo_control/features/users/data/datasources/local_users_datasource.dart';
import 'package:smoo_control/features/users/data/repositories/users_repository.dart';
import 'package:smoo_control/features/users/domain/repositories/i_users_repository.dart';
import 'package:smoo_control/features/users/presentation/bloc/users_bloc.dart';

part 'service_locator_catalog_part.dart';
part 'service_locator_core_part.dart';
part 'service_locator_operations_part.dart';
part 'service_locator_settings_part.dart';
part 'service_locator_sync_part.dart';

/// Global dependency container for the application.
final GetIt serviceLocator = GetIt.instance;

/// Registers application dependencies.
Future<void> configureDependencies() async {
  await serviceLocator.reset();
  _registerCoreDependencies();
  _registerCatalogDependencies();
  _registerOperationsDependencies();
  _registerSettingsAndAdminDependencies();
  _registerSalesAndSyncDependencies();

  registerAuthDependencies(serviceLocator);
  registerPosDependencies(serviceLocator);
}
